# Generated by Django 6.0.7 on 2026-07-31 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='label')),
                ('token_prefix', models.CharField(db_index=True, max_length=16, verbose_name='token prefix')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token hash')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('revoked', 'revoked')], default='pending', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_enrollments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_enrollments', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'agent enrollment',
                'verbose_name_plural': 'agent enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
