# Generated by Django 6.0.7 on 2026-07-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentenrollment',
            name='agent_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='agent version'),
        ),
        migrations.AddField(
            model_name='agentenrollment',
            name='cf_tunnel_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Cloudflare tunnel id'),
        ),
        migrations.AddField(
            model_name='agentenrollment',
            name='db_folder',
            field=models.CharField(blank=True, max_length=500, verbose_name='database folder'),
        ),
        migrations.AddField(
            model_name='agentenrollment',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, verbose_name='hostname'),
        ),
        migrations.AddField(
            model_name='agentenrollment',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='operating system'),
        ),
        migrations.AddField(
            model_name='agentenrollment',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registered at'),
        ),
    ]
