# Generated by Django 6.0.7 on 2026-07-31 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentenrollment_agent_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, verbose_name='kind')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('done', 'done'), ('failed', 'failed')], default='queued', max_length=16, verbose_name='status')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='result')),
                ('error', models.CharField(blank=True, max_length=600, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='accounts.agentenrollment')),
            ],
            options={
                'verbose_name': 'agent command',
                'verbose_name_plural': 'agent commands',
                'ordering': ['created_at'],
            },
        ),
    ]
