# Generated by Django 6.0.7 on 2026-08-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agentcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('stopped', 'stopped'), ('revoked', 'revoked')], default='pending', max_length=16, verbose_name='status'),
        ),
    ]
