# Generated by Django 6.0.7 on 2026-08-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_agentenrollment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prefix', models.CharField(db_index=True, max_length=16, verbose_name='code prefix')),
                ('code_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='code hash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='consumed at')),
                ('consumed_from', models.GenericIPAddressField(blank=True, null=True, verbose_name='consumed from')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='accounts.agentenrollment')),
            ],
            options={
                'verbose_name': 'agent activation code',
                'verbose_name_plural': 'agent activation codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
